# Config variables:
#   ${full_timer_name}: "function_name [file_path {start}-{end}]"

instrumentation: TAU
include:
  - <Profile/Profiler.h>

main_insert:
  - "    TAU_PROFILE_TIMER(tautimer, \"${full_timer_name}\", \" \", TAU_DEFAULT);"
  - "    TAU_INIT(&argc, &argv);"
  - "#ifndef TAU_MPI"
  - "#ifndef TAU_SHMEM"
  - "    TAU_PROFILE_SET_NODE(0);"
  - "#endif /* TAU_SHMEM */"
  - "#endif /* TAU_MPI */"
  - "    TAU_PROFILE_START(tautimer);"

function_begin_insert:
  - "    TAU_PROFILE_TIMER(tautimer, \"${full_timer_name}\", \" \", TAU_USER);"
  - "    TAU_PROFILE_START(tautimer);"

function_end_insert:
  - "TAU_PROFILE_STOP(tautimer);"

Fortran:
# Config variables:
#   ${full_timer_name}: "procedure_name [file_path {start}-{end}]"
  instrumentation: tauFortran
  program_insert:
    - |-2
      ! SALT-FM injected TAU instrumentation
            integer, save :: tauProfileTimer(2) = [0, 0]
            call TAU_PROFILE_INIT()
            call TAU_PROFILE_TIMER(tauProfileTimer, "${full_timer_name}&
           &")
            call TAU_PROFILE_START(tauProfileTimer)
      #ifndef TAU_MPI
            call  TAU_PROFILE_SET_NODE(0)
      #endif

  procedure_begin_insert:
    - |-2
      ! SALT-FM injected TAU instrumentation
            integer, save :: tauProfileTimer(2) = [0, 0]
            call TAU_PROFILE_TIMER(tauProfileTimer, "${full_timer_name}&
           &")
            call TAU_PROFILE_START(tauProfileTimer)

  procedure_end_insert:
    - |-2
      ! SALT-FM injected TAU instrumentation
            call TAU_PROFILE_STOP(tauProfileTimer)

  pure_procedure_begin_insert:
    - |-2
      ! SALT-FM injected TAU instrumentation
            call TAU_START("&${full_timer_name}&
           &")

  pure_procedure_end_insert:
    - |-2
      ! SALT-FM injected TAU instrumentation
            call TAU_STOP("${full_timer_name}&
           &")