name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: paratools/salt-dev:latest
    steps:
      - uses: actions/checkout@v3
      - name: Print working directory
        run: |
            echo "Working directory: $(pwd)"
            echo "Working directory contents:"
            ls -la
      - name: Configure SALT
        run: cmake -Wdev -Wdeprecated -G Ninja -S . -B build
      - name: Compile SALT
        run: |
          echo "Cores: $(nproc)"
          cmake --build build --parallel $(nproc) || cmake --build build --verbose
