name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: paratools/salt-dev:0.2
    steps:
      - uses: actions/checkout@v3
      - name: Print working directory
        run: |
            echo "Working directory: $(pwd)"
            echo "Working directory contents:"
            ls -la
      - name: Configure SALT
        run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Wdev -Wdeprecated -G Ninja -S . -B build
      - name: Compile SALT
        run: |
          echo "Cores: $(nproc) "
          cmake --build build --parallel $(nproc) || cmake --build build --verbose
      - name: Run Tests
        run: cd build && ctest --output-on-failure
