name: CI
on: push
env: 
  GIT_SSL_NO_VERIFY: true
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: paratools/salt-dev:1.3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: patch TAU & link flang
        run: |
          sed -i 's/#FLANG_NO_MX_OPTS#//' /usr/local/x86_64/lib/Makefile.tau-clang-pthread || echo "sed command returned non-zero status"
          if ! [ -e /usr/local/bin/flang ]; then
            echo "Linking flang-new as flang"
            ln -s /usr/local/bin/flang-new /usr/local/bin/flang
          else
            ls -la /usr/local/bin/flang
          fi
          tau_f90.sh -show
          tau_f90.sh --version
      - name: Print working directory
        run: |
            echo "Working directory: $(pwd)"
            echo "Working directory contents:"
            ls -la
      - name: Configure SALT
        run: cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -Wdev -Wdeprecated -G Ninja -S . -B build
      - name: Compile SALT
        run: |
          echo "Cores: $(nproc) "
          cmake --build build --parallel $(nproc) || cmake --build build --verbose
      - name: Run Tests
        run: cd build && ctest -j --output-on-failure || ctest --rerun-failed --verbose
