name: lint
on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - uses: astral-sh/setup-uv@v8.1.0
      - name: Install cmake-lint
        run: uv tool install cmakelang --with pyyaml
      - name: shellcheck
        run: |
          shellcheck --shell=bash \
            activate-salt-fm-env.sh \
            build_and_test.sh \
            .githooks/pre-commit \
            .githooks/pre-push \
            src/fparse-llvm.in \
            src/saltfm.in
      - name: cmake-lint
        run: cmake-lint CMakeLists.txt cmake/modules/*.cmake
